// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using deprem.Database.Data;

#nullable disable

namespace deprem.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230403020305_mg2")]
    partial class mg2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("deprem.Model.Models.Deprem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<double>("boylam")
                        .HasColumnType("float");

                    b.Property<string>("cozumNiteliği")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("derinlik")
                        .HasColumnType("float");

                    b.Property<double>("enlem")
                        .HasColumnType("float");

                    b.Property<double>("md")
                        .HasColumnType("float");

                    b.Property<double>("ml")
                        .HasColumnType("float");

                    b.Property<double>("mw")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("saat")
                        .HasColumnType("time");

                    b.Property<DateTime>("tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("yer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Depremler");
                });
#pragma warning restore 612, 618
        }
    }
}
